/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainLinkSol from "./ChainLink.sol";
export type { chainLinkSol };
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as gFarm2TokenSol from "./GFarm2Token.sol";
export type { gFarm2TokenSol };
import type * as gFarmTradingStorageV5Sol from "./GFarmTradingStorageV5.sol";
export type { gFarmTradingStorageV5Sol };
import type * as gnsPairInfosV61Sol from "./GNSPairInfosV6_1.sol";
export type { gnsPairInfosV61Sol };
import type * as gnsPairStorageV6Sol from "./GNSPairStorageV6.sol";
export type { gnsPairStorageV6Sol };
import type * as gnsPriceAggregatorV63 from "./GNSPriceAggregatorV6_3";
export type { gnsPriceAggregatorV63 };
import type * as gnsStakingV62Sol from "./GNSStakingV6_2.sol";
export type { gnsStakingV62Sol };
import type * as gnsTradingV61Sol from "./GNSTradingV6_1.sol";
export type { gnsTradingV61Sol };
