/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as storageInterfaceV5Sol from "./StorageInterfaceV5.sol";
export type { storageInterfaceV5Sol };
export type { CallbacksInterfaceV6_2 } from "./CallbacksInterfaceV6_2";
export type { ChainlinkFeedInterfaceV5 } from "./ChainlinkFeedInterfaceV5";
export type { IGToken } from "./IGToken";
export type { PairsStorageInterfaceV6 } from "./PairsStorageInterfaceV6";
export type { TokenInterfaceV5 } from "./TokenInterfaceV5";
