/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GNSStakingV6_2 } from "./GNSStakingV6_2";
export type { TokenInterfaceV5 } from "./TokenInterfaceV5";
