/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VaultInterfaceV5,
  VaultInterfaceV5Interface,
} from "../../../contracts/GNSPairStorageV6.sol/VaultInterfaceV5";

const _abi = [
  {
    inputs: [],
    name: "currentBalanceDai",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "distributeRewardDai",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "receiveDaiFromTrader",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "sendDaiToTrader",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class VaultInterfaceV5__factory {
  static readonly abi = _abi;
  static createInterface(): VaultInterfaceV5Interface {
    return new utils.Interface(_abi) as VaultInterfaceV5Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VaultInterfaceV5 {
    return new Contract(address, _abi, signerOrProvider) as VaultInterfaceV5;
  }
}
