/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GNSStakingV6_2__factory } from "./GNSStakingV6_2__factory";
export { TokenInterfaceV5__factory } from "./TokenInterfaceV5__factory";
