/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as chainLinkSol from "./ChainLink.sol";
export * as erc20Sol from "./ERC20.sol";
export * as gFarm2TokenSol from "./GFarm2Token.sol";
export * as gFarmTradingStorageV5Sol from "./GFarmTradingStorageV5.sol";
export * as gnsPairInfosV61Sol from "./GNSPairInfosV6_1.sol";
export * as gnsPairStorageV6Sol from "./GNSPairStorageV6.sol";
export * as gnsPriceAggregatorV63 from "./GNSPriceAggregatorV6_3";
export * as gnsStakingV62Sol from "./GNSStakingV6_2.sol";
export * as gnsTradingV61Sol from "./GNSTradingV6_1.sol";
