/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AggregatorInterfaceV5 } from "./AggregatorInterfaceV5";
export type { GFarmTradingStorageV5 } from "./GFarmTradingStorageV5";
export type { PausableInterfaceV5 } from "./PausableInterfaceV5";
export type { PoolInterfaceV5 } from "./PoolInterfaceV5";
export type { TokenInterfaceV5 } from "./TokenInterfaceV5";
