/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ChainlinkFeedInterfaceV5,
  ChainlinkFeedInterfaceV5Interface,
} from "../../../../../contracts/GNSPriceAggregatorV6_3/contracts/interfaces/ChainlinkFeedInterfaceV5";

const _abi = [
  {
    inputs: [],
    name: "latestRoundData",
    outputs: [
      {
        internalType: "uint80",
        name: "",
        type: "uint80",
      },
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint80",
        name: "",
        type: "uint80",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ChainlinkFeedInterfaceV5__factory {
  static readonly abi = _abi;
  static createInterface(): ChainlinkFeedInterfaceV5Interface {
    return new utils.Interface(_abi) as ChainlinkFeedInterfaceV5Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChainlinkFeedInterfaceV5 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ChainlinkFeedInterfaceV5;
  }
}
