/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as storageInterfaceV5Sol from "./StorageInterfaceV5.sol";
export { CallbacksInterfaceV6_2__factory } from "./CallbacksInterfaceV6_2__factory";
export { ChainlinkFeedInterfaceV5__factory } from "./ChainlinkFeedInterfaceV5__factory";
export { IGToken__factory } from "./IGToken__factory";
export { PairsStorageInterfaceV6__factory } from "./PairsStorageInterfaceV6__factory";
export { TokenInterfaceV5__factory } from "./TokenInterfaceV5__factory";
